### ISSUE TITLE
Feedback on week 9 project progress for CS2113T-T09-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T09-1/main#167]
## Team progress for `v1.2`
* [ ] Team PR created to the upstream repository with the title `[AY1920S1-CS2113T-T09-1] Contact List Pro`(:exclamation:)
* Milestone `v1.2` properly managed:
   * [x] A suitable deadline 2019-10-09 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-T09-1/main/issues/166 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/165 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/164 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/163 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/157 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/156 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/154 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/153 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/152 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/151 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/127 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/126 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/124 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/123 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/122 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/118 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/117 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/116 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/115 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/114 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/111 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/99 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/98 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/90 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/85 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/84 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/82 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/81 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/80 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/79 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/78 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/77 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/76 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/75 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/72 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/71 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/70 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/69 (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
   * [x] Code tagged as `v1.2`(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.2` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone v1.3 planned:
   * [x] A suitable deadline 2019-10-23 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-T09-1/main/issues/162 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/161 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/160 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/159 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/158 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/155 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/149 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/148 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/147 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/146 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/145 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/142 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/141 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/140 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/139 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/138 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/137 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/133 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/131 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/129 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/120 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/119 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/74 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/73 (:heavy_check_mark: well done!)
## Individual progress of @yzia2000 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/85 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/76 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/72 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/69 (:heavy_check_mark: well done!)
## Individual progress of @nystera for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/166 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/114 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/99 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/70 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/69 (:heavy_check_mark: well done!)
## Individual progress of @ngjiewu for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/98 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/90 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/71 (:heavy_check_mark: well done!)
## Individual progress of @jingkang97 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/69 (:heavy_check_mark: well done!)
## Individual progress of @enriquekhai for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/111 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/84 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/75 (:heavy_check_mark: well done!)

Tutor: @seanieyap

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-17 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
