### ISSUE TITLE
Feedback on week 10 project progress for CS2113T-T09-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T09-1/main#185]
## Team progress for mid `v1.3`
* Milestone `v1.3` properly managed:
   * [x] A suitable deadline 2019-10-23 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-T09-1/main/issues/182 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/181 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/180 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/178 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/177 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/176 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/174 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/173 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/162 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/161 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/160 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/159 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/158 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/155 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/149 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/148 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/147 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/146 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/145 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/142 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/141 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/140 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/139 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/138 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/137 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/133 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/131 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/129 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/120 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/119 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/108 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/92 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/88 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/74 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/73 (:heavy_check_mark: well done!)
* [ ] New JAR released on GitHub.(:exclamation: try to do by next milestone)
* Milestones setup:
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
## Individual progress of @yzia2000 for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/177 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/174 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/173 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/159 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/149 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/148 (:heavy_check_mark: well done!)
## Individual progress of @nystera for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/pull/181 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/180 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/178 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/182 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/176 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/158 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/142 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/137 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/133 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/119 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/92 (:heavy_check_mark: well done!)
## Individual progress of @ngjiewu for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/147 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/139 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/131 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/108 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/88 (:heavy_check_mark: well done!)
## Individual progress of @jingkang97 for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/147 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/141 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/140 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/129 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/120 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/92 (:heavy_check_mark: well done!)
## Individual progress of @enriquekhai for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/162 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/161 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/146 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/145 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/138 (:heavy_check_mark: well done!)

Tutor: @seanieyap

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-24 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
