### ISSUE TITLE
Feedback on week 11 project progress for CS2113T-T09-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T09-1/main#249]
## Team progress for `v1.3`
* Milestone `v1.3` properly managed:
   * [x] A suitable deadline 2019-10-30 set(:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the last 7 days (:heavy_check_mark: well done!)
* [ ] `Ui.png` has been updated in the last 7 days (:exclamation: try to do by next milestone)
* Milestones setup:
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
## Individual progress of @yzia2000 for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/245 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/207 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/202 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/196 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/177 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/174 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/173 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/159 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/148 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/119 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)
## Individual progress of @nystera for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/pull/181 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/180 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/178 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/224 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/223 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/222 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/221 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/216 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/215 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/196 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/182 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/176 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/158 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/142 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/137 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/133 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/119 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/92 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)
## Individual progress of @ngjiewu for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/204 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/196 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/139 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/131 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/119 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/108 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/88 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)
## Individual progress of @jingkang97 for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/196 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/141 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/129 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/119 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/92 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)
## Individual progress of @enriquekhai for`v1.3`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks(:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.3` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/204 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/196 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/162 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/161 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/146 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/145 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/138 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/119 (:heavy_check_mark: well done!)
* [not graded] Ensured the code is [RepoSense  compatible](https://nuscs2113-ay1920s1.github.io/website/admin/project-w10-mid-v13.html) and your code contributions are showing code correctly (:question: tick this yourself after completing the item)

Tutor: @seanieyap

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-31 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
