### ISSUE TITLE
Feedback on week 12 project progress for CS2113T-T09-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T09-1/main#291]
## Team progress for mid-`v1.4`
* Milestones setup:
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone `v1.4` properly managed:
   * [ ] A suitable deadline 2019-11-13 set(:exclamation: try to do by next milestone)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-T09-1/main/issues/289 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/285 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/283 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/279 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/272 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/271 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/268 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/267 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/263 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/260 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/259 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/258 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/251 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/150 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/149 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/147 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/144 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/143 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/140 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/136 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/135 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/134 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/130 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/121 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/120 (:heavy_check_mark: well done!)
## Individual progress of @yzia2000 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/289 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/149 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/143 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @nystera for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/144 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/130 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @ngjiewu for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/pull/285 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/285 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/283 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/279 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/272 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/271 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/268 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/267 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/260 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/259 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/258 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/251 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/147 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/143 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/135 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @jingkang97 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/147 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/140 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/136 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/121 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/120 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @enriquekhai for mid-`v1.4`
* [ ] Merged updates to code (Java/FXML) files during the past 2 weeks (:exclamation: try to do by next milestone)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/134 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @seanieyap

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-07 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
