### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-T09-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-T09-1/main#344]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @yzia2000 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/289 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/270 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/143 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @nystera for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/327 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/319 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/317 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/300 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/298 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/281 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/144 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @ngjiewu for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/pull/285 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/285 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/283 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/279 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/272 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/271 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/268 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/267 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/260 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/259 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/258 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/251 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/143 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/135 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @jingkang97 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/pull/304 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/297 https://github.com/AY1920S1-CS2113T-T09-1/main/pull/286 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/309 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/308 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/307 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/306 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/121 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/120 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @enriquekhai for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-T09-1/main/issues/309 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/296 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/295 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/282 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/278 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/274 https://github.com/AY1920S1-CS2113T-T09-1/main/issues/265 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @seanieyap

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
